version: '3.1'

services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8092:80
    environment:
      WORDPRESS_DB_HOST: 127.0.0.1:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: t_wordpress
    volumes:
      - ${WORDPRESS_DIR}/data:/var/www/html
