version: '2'
services:
  kafka:
    image: andahme/kafka
    ports:
      - "9092:9092"
    environment:
            KAFKA_BROKER_LIST: kafka:9092
            KAFKA_SERVER: kafka:9092
            KAFKA_ZOOKEEPER_CONNECT: 118.25.36.41:2181
    volumes:
          - "${KAFKA_DIR}/data:/var/lib/kafka"
            #          - "${KAFKA_DIR}/config:/opt/kafka/config/"
