version: '3'

services:
  redis:
    container_name: reids-docker        # 指定容器的名称
    image: redis                   # 指定镜像和版本,如果是树莓派，必须选择对应架构版本的镜像，不然无法运行
    restart: always
    command: --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - "${REDIS_DIR}/data:/data"           # 挂载数据目录
      - "${REDIS_DIR}/config/redis.conf:/usr/local/etc/redis/redis.conf"      # 挂载配置文件目录
